[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "1.4.11"
authors = ["Azalea Gui <azalea@hydev.org>"]
edition = "2021"
rust-version = "1.75.0"
description = "Neofetch with LGBTQ+ pride flags!"
repository = "https://github.com/hykilpikonna/hyfetch"
license = "MIT"

[workspace.dependencies]
ansi_colours = { version = "1.2.2", default-features = false }
anyhow = { version = "1.0.86", default-features = false }
bpaf = { version = "0.9.12", default-features = false }
derive_more = { version = "1.0.0-beta.6", default-features = false }
env_logger = { version = "0.11.3", default-features = false }
indexmap = { version = "2.2.6", default-features = false }
log = { version = "0.4.21", default-features = false }
rgb = { version = "0.8.37", default-features = false }
strum = { version = "0.26.3", default-features = false }
